coreos-kernel: Fix kernel builds, broken by update to ccache 3.2.1
Apparently didn't recompile enough stuff to test the ccache change. From
the ccache 3.2 release notes:

    ccache no longer passes preprocessor options like -D and -I to the
    compiler when compiling preprocessed output. This fixes warnings
    emitted by clang.

The hardened compiler, at least as of gcc-4.8.3, uses -D__KERNEL__ to
detect kernel compiles and in that case avoids enabling PIE by default.
Mixing PIE and kernel compiles can lead to the following error:

    error: code model kernel does not support PIC mode

Upstream bug: https://bugs.gentoo.org/show_bug.cgi?id=535984