sys-apps/kexec-tools: update to 2.0.22
Update sys-apps/kexec-tools to 2.0.22, as needed by gcc 10.
Without that update, build fails like:

```
/usr/libexec/gcc/x86_64-cros-linux-gnu/ld:
kexec/arch/x86_64/kexec-bzImage64.o:.../kexec/arch/x86_64/kexec-bzImage64.c:45:
multiple definition of `bzImage_support_efi_boot';
kexec/arch/i386/kexec-bzImage.o:.../kexec/arch/i386/kexec-bzImage.c:43:
first defined here
```