profiles: update sys-devel/gcc to 11.3.1_p20230120-r1
Since the new USE flag `cet` became the default in profiles of
portage-stable, SDK bootstrap using gcc 11.3.1_p20221209 started
to fail at `sys-libs/glibc`.

```
in function `dl_open_worker_begin':
 dl-open.c:(.text+0xab4c): undefined reference to `_dl_cet_open_check'
```

That is because gcc is not correctly configured for CET.

That issue was fixed in recent upstream GCC versions,
e.g. 11.3.1_p20221209-r1 or 11.3.1_p20230120-r1.
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=016184c289f2cc6c6ade496a700a12f135fbae07
https://gitweb.gentoo.org/proj/gcc-patches.git/commit/?id=15daf0510a5fab17cd556261d688a6618391a0c1
However, gcc of Flatcar, 11.3.1_p20221209, does not have the fix.

Update sys-devel/gcc to 11.3.1_p20230120-r1 to fix that issue.

Also accept ~arm64 to keep the same version for both arches.