net-analyzer/netperf: update to 2.7.0-r3
Update net-analyzer/netperf to 2.7.0-r3, as needed by gcc 10.
Without that update, build fails like:

```
/usr/libexec/gcc/x86_64-cros-linux-gnu/ld:
nettest_omni.o:.../src/nettest_omni.c:455: multiple definition of `loc_nodelay';
nettest_omni.o:.../src/nettest_omni.c:455: multiple definition of `loc_nodelay';
nettest_bsd.o:.../src/nettest_bsd.c:206: first defined here
```