sys-fs/overlaybd: add overlaybd file system and tools
WORK IN PROGRESS: This commit will be AMENDED.

This change introduces overlaybd, a novel layering block-level image
format for containers.
See https://containerd.github.io/overlaybd/ for more information.

It also adds a set of tools for making use of overlaybd, in
sys-fs/accelerated-container-image. Specifically, these are
* a custom ctr for pulling accelerated container images
* an image converter
* a snapshotter

TODO:
- make src_compile succeed

overlaybd compile issues:

- sys-fs/overlaybd-1.0.15-r0/work/overlaybd-1.0.15/src/overlaybd/tar/test/test.cpp:17:10: fatal error: gtest/gtest.h: No such file or directory

arm64

In general, cmake eclass seems to not pass cross compile environment
down to upstream's source deps.

- wrong linker module in erofs configure stage
  /usr/libexec/gcc/aarch64-cros-linux-gnu/ld -m elf_x86_64
- aarch64-cros-linux-gnu-g++: error: unrecognized command-line option '-msse4.2'

Signed-off-by: Thilo Fromm <thilofromm@microsoft.com>