profiles: accept unstable aardvark-dns
this solves a compiling issue with Rust 1.80 (because of the 'time'
dependency).

```
error[E0282]: type annotations needed for `Box<_>`
```

Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>